services:
#this tests if nvidia works
  # test:
  #   image: nvidia/cuda:12.9.0-base-ubuntu22.04
  #   command: nvidia-smi
  #   deploy: {} # Needed for Compose v3.8+ for device_requests on Swarm. Otherwise, omit or run locally.
  #   runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all

  ollama-server:
    image: ollama/ollama:latest
    container_name: 401r-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: 401r-ollama-webui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://401r-ollama:11434
    volumes:
      - ./webui:/app/backend/data
    ports:
      - "3010:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

